<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>CombatModelBlocker</AssemblyName>
    <RootNamespace>CombatModelBlocker</RootNamespace>
    <AssemblyVersion>1.0.6.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <IsPackable>false</IsPackable>
    <Authors>QianyanSR</Authors>
    <RepositoryType>Git</RepositoryType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Configuration.cs" />
    <Compile Include="OldStableNotice.cs" />
    <Compile Include="Plugin.cs" />
  </ItemGroup>
</Project>
