<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>QToolKit</AssemblyName>
    <RootNamespace>QToolKit</RootNamespace>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <IsPackable>false</IsPackable>
    <Authors>QianyanSR</Authors>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>
</Project>
